apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: skn-cluster-01-super001
  labels:
    strimzi.io/cluster: skn-cluster-01 
spec:
  authentication:
    type: scram-sha-512 
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operations:
          - Write
          - Read
          - Create
          - Delete
          - Alter
          - Describe
          - ClusterAction
          - DescribeConfigs
          - AlterConfigs
      - resource:
          type: group
          name: '*'
          patternType: literal
        operations:
          - Write
          - Read
          - Create
          - Delete
          - Alter
          - Describe
          - ClusterAction
          - DescribeConfigs
          - AlterConfigs
      - resource:
          type: cluster
          name: '*'
          patternType: literal
        operations:
          - Write
          - Read
          - Create
          - Delete
          - Alter
          - Describe
          - ClusterAction
          - DescribeConfigs
          - AlterConfigs
          - IdempotentWrite