apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: skn-cluster-01-topic001
  labels:
    strimzi.io/cluster: skn-cluster-01
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824

---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: skn-cluster-01-topic002
  labels:
    strimzi.io/cluster: skn-cluster-01
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
